### ISSUE TITLE
completion-menu overlap with cmdline view

### ISSUE THREAD

**Issue by ranjithshegde** [folke/noice.nvim#134]
**Describe the bug**
Using `cmdline` view places the popup (**not** nvim-cmp) completion menu on top of cmdline, Cant see what is being typed
Also, the highlight for the currently selected item from popupmenu is no longer visible

**Screenshots**
![overlap](https://user-images.githubusercontent.com/10258296/198144089-efd0c92c-5fe8-4ee3-866a-d51fb5e7a693.gif)

**config**
```lua
    require('noice').setup {
        cmdline = {
            view = 'cmdline',
            view_search = 'cmdline',
            format = {
                inc_rename = { pattern = '^:%s*IncRename%s+', icon = ' ', ft = 'text' },
            },
        },
        lsp = { hover = { enabled = true } },
        views = { hover = { border = { style = 'single' } } },
    }
```

**Comment by folke** [comment]
Fixed!

**Comment by ranjithshegde** [comment]
Thank you for the quick fix!
The highlight for current selection inside the completion popup is still missing. The highlight used to be present

**Comment by folke** [comment]
Highlight works for me. Not sure what the problem is. Can you check with a minimal.lua?
https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by folke** [comment]
Feel free to open a new issue :)

**Comment by ranjithshegde** [comment]
@folke Is it not a highlight but a cursorline?
I have an autocmd that disables cursorline, when i comment out that autocmd the "highlight" works

**Comment by folke** [comment]
Yes! That's it indeed. NuiMenu uses the cursorline for that

**Comment by folke** [comment]
If you want to enable/disable the cursorline in active windows, use this:

```lua
-- show cursor line only in active window
vim.api.nvim_create_autocmd({ "InsertLeave", "WinEnter" }, {
  callback = function()
    local ok, cl = pcall(vim.api.nvim_win_get_var, 0, "auto-cursorline")
    if ok and cl then
      vim.wo.cursorline = true
      vim.api.nvim_win_del_var(0, "auto-cursorline")
    end
  end,
})
vim.api.nvim_create_autocmd({ "InsertEnter", "WinLeave" }, {
  callback = function()
    local cl = vim.wo.cursorline
    if cl then
      vim.api.nvim_win_set_var(0, "auto-cursorline", cl)
      vim.wo.cursorline = false
    end
  end,
})
```

**Comment by ranjithshegde** [comment]
Thanks! Your method is very straight forward. 
Mine was too aggressive with `FocusGained` `FocusLost` autocmds added into the mix, + file-match &filetype to selectively disable.
