### ISSUE TITLE
Lsp signature fails for Solargraph

### ISSUE THREAD

**Issue by pBorak** [folke/noice.nvim#162]
**Describe the bug**
With LSP signature help enabled there's an error for some LSP, namely Solargraph. The issue is well-known issue and comes down to how Solargraph reports activeParamete. Some users have already reported it in another nvim plugin that gives this signature help functionality [here](https://github.com/ray-x/lsp_signature.nvim/issues/42) and [here](https://github.com/ray-x/lsp_signature.nvim/issues/51).

**To Reproduce**
1. Trigger LSP signature in Ruby file with Solargraph LSP.

**Expected Behavior**
Lsp signature pop-ups without highlighting active parameters.

**Screenshots**

<img width="1486" alt="Screenshot 2022-10-29 at 09 27 56" src="https://user-images.githubusercontent.com/45797239/198819677-d1ef06be-ea39-4f5d-9273-e13b6056a867.png">

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>

Sat Oct 29 09:27:53 2022
...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:118: attempt to index field 'parameters' (a nil value)

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function '__index'
	...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:118: in function 'active_parameter'
	...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:155: in function 'format_signature'
	...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:169: in function 'format'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/lsp/init.lua:193: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/lsp/init.lua:179>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'signature'
	...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:91: in function 'handler'
	...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

</pre>
</details>

**Comment by folke** [comment]
Fixed

**Comment by pBorak** [comment]
@folke Sadly, after your fix, it still fails but in other place

```lua
Sat Oct 29 10:30:30 2022
...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:124: attempt to index local 'param' (a number value)

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function '__index'
	...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:124: in function 'format_active_parameter'
	...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:157: in function 'format_signature'
	...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:169: in function 'format'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/lsp/init.lua:193: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/lsp/init.lua:179>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'signature'
	...e/pack/packer/opt/noice.nvim/lua/noice/lsp/signature.lua:91: in function 'handler'
	...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

```

**Comment by folke** [comment]
My fix was wrong. Should be ok now

**Comment by pBorak** [comment]
Yep, it works great now. Thanks!

**Comment by folke** [comment]
Can you check if it's really empty?

Focus on the doc window and select all lines to see them non-concealed

**Comment by folke** [comment]
I just pushed a fix to not show empty messages. So if yours is effectively empty, it should not show now anymore

**Comment by pBorak** [comment]
It seems it was really empty (I could not select anything there). Indeed your fix solved it. Cheers!
