### ISSUE TITLE
search count messages do not show in Statusline Components

### ISSUE THREAD

**Issue by philipGaudreau** [folke/noice.nvim#217]
**Describe the bug**
Since commit e5092c2 (#211), the search count message does not appear in status line. What is weird is that the first result has a search count, but subsequent `n/N` matchs and searches do not. Status line config can be seen in GIF.

**Which version of Neovim are you using?**
NVIM v0.9.0-dev-296+g7335a67b5

**To Reproduce**
1. It was "working" (although disappearing) in fb0e3b0.

**Expected Behavior**
Search count in status line.

**Screenshots**
![demo](https://user-images.githubusercontent.com/22773951/201501306-93820c4f-2ea2-43df-8c19-2486ad31f6d7.gif)

**Noice Log**
Nothing relevant.

**Comment by folke** [comment]
I assume you had `vim.go.hlsearch = false` set in your config? That didn't work as intended. Should be fixed now!

**Comment by philipGaudreau** [comment]
Hi, sorry for the late response.

I tested it on c11d1c6 and unfortunately, it is still the same behaviour as before. Also, as you mentioned, I have `vim.go.hlsearch = false`. I tried setting it to `true`, but the problem is still there.

**Comment by folke** [comment]
It really should work now. Are you sure you updated?
And it already workes with hlsearch=true.

What is your Noice config?

**Comment by philipGaudreau** [comment]
> Are you sure you updated?

Yes I previously had 7b62ccf stapled in packer (`commit = ...`) and the feature was working. I removed that option, updated, and double checked the git repo sha in `.local/share/nvim/...` and it was c11d1c6.

My config is as follow:

```lua
require("noice").setup({
  popupmenu = {
    enabled = false, -- enables the Noice popupmenu UI
  },
  notify = {
    enabled = false,
  },
  lsp = {
    progress = {
      enabled = false,
    },
    override = {
      -- override the default lsp markdown formatter with Noice
      ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
      -- override the lsp markdown formatter with Noice
      ["vim.lsp.util.stylize_markdown"] = true,
    },
    documentation = {
      view = "hover",
      opts = {
        lang = "markdown",
        replace = true,
        render = "plain",
        format = { "{message}" },
        win_options = { concealcursor = "n", conceallevel = 3 },
      },
    },
  },
  presets = {
    lsp_doc_border = true
  },
  routes = {
    {
      filter = {
        event = "msg_show",
        ["not"] = {
          kind = { "confirm", "confirm_sub" },
        },
      },
      opts = { skip = true },
    },
  },
})
```

**Comment by folke** [comment]
You will want to remove that `lang=markdown`. That's no longer needed and will lead to rendering issues most likely.
Also be aware that you're skipping all messages? So command output, errors, ...

Apart from that all works as expected with your config for me.

Please provide a https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by folke** [comment]
Also, what is your statusline config?

**Comment by philipGaudreau** [comment]
I was able to get a complete reproductible example with that:

[minimal.txt](https://github.com/folke/noice.nvim/files/10016383/minimal.txt)

**Comment by folke** [comment]
You're getting the last message in the statusline, not `search`. Please check the docs

**Comment by philipGaudreau** [comment]
Oh! Now I get it, thanks! I was searching at the wrong place since the behaviour changed in updating to latest commit. My apologies for the trouble, I did not read the docs correctly.
