### ISSUE TITLE
feature-request: `lsp_progress` max entry amount

### ISSUE THREAD

**Issue by dtomvan** [folke/noice.nvim#285]
**Is your feature request related to a problem? Please describe.**
It's very annoying (for example when using the sumneko_lua lsp server) to have ~10 `lsp_progress` spinners.
Sometimes it even overlaps with some code when the text gets too long.

**Describe the solution you'd like**
A configuration variable (`config.lsp.progress.max`?) which specifies how much spinners are able to show up at once. It would then only display at most the amount of spinners specified. Default would probably then be `nil`, for backwards compatibility. One could then set it to `1`, and it would only show the most recently added spinner.

**Describe alternatives you've considered**
- Disabling the spinner entirely: defeats the purpose, but it does declutter
- Only show bar/spinner: also declutters but I would like to see what the LSP is doing, so isn't ideal either

**Additional context**
![image](https://user-images.githubusercontent.com/51440893/209826732-be6ac503-4475-4165-ad2b-5428fb416466.png)

**Comment by folke** [comment]
That's a very specific use-case. Won't add this. If it bothers you, you can always disable the noice integration for lsp progress

**Comment by dtomvan** [comment]
Ah alright, still very nice project tho 😄

**Comment by gegoune** [comment]
Just to add to issue before it gets to old. When updating plugins with packer and having neodev.nvim set up I get a wall of sumneko notifications, one for each plugin with lua files I believe. 

I know it's not directly noice's, sumneko must be sending progress for each workspace I believe(?) but perhaps something could be done? Since you closed this issue already I wondered what would you suggest next? Open issue with sumneko? Not quite sure where root cause lies here. 

Happy new your! :)

**Comment by folke** [comment]
That is super odd, but makes sense in a way, since a lot of files changed in your workspace. But I still only see two progress notifs of reloading the workspace, so not sure why you see all those messages.

I did optimize my sumneko config though. Try the below:

```lua
    sumneko_lua = {
      -- cmd = { "/home/folke/projects/lua-language-server/bin/lua-language-server" },
      single_file_support = true,
      settings = {
        Lua = {
          workspace = {
            checkThirdParty = false,
          },
          completion = {
            workspaceWord = true,
            callSnippet = "Both",
          },
          misc = {
            parameters = {
              "--log-level=trace",
            },
          },
          diagnostics = {
            -- enable = false,
            groupSeverity = {
              strong = "Warning",
              strict = "Warning",
            },
            groupFileStatus = {
              ["ambiguity"] = "Opened",
              ["await"] = "Opened",
              ["codestyle"] = "None",
              ["duplicate"] = "Opened",
              ["global"] = "Opened",
              ["luadoc"] = "Opened",
              ["redefined"] = "Opened",
              ["strict"] = "Opened",
              ["strong"] = "Opened",
              ["type-check"] = "Opened",
              ["unbalanced"] = "Opened",
              ["unused"] = "Opened",
            },
            unusedLocalExclude = { "_*" },
          },
          format = {
            enable = false,
            defaultConfig = {
              indent_style = "space",
              indent_size = "2",
              continuation_indent_size = "2",
            },
          },
        },
      },
    },
```

Remove the strong and strict if you dont want that.

**Comment by dtomvan** [comment]
> not sure why you see all those messages.

I think it's because of this setting in my config which loads all lua files in my DotFiles (~120):

```lua
-- require'lspconfig'.sumneko_lua.setup { <snip>
       root_dir = require('lspconfig.util').find_git_ancestor,
-- }
```

**Comment by dtomvan** [comment]
Side note: this is one of the other weird things the progress bar does, and when I was using fidget.nvim this also happened, even with only 1 LSP attached.
![image](https://user-images.githubusercontent.com/51440893/210137220-42816a20-7464-413d-b41c-df564b0f65e7.png)

**Comment by folke** [comment]
That is completely normal. Check the faq on sumneko. You will always see two instances

**Comment by gegoune** [comment]
@folke just to update you: I haven't seen that wall of notifications in a while now, not sure if it got fixed by noice, neodev.nvim or lua_ls. Will provide you with more information should issue resurface in the future.

Thanks for great work!

**Comment by MariaSolOs** [comment]
Just leaving this here for future reference: This might not be the best way to do it, but I added this configuration to my routes to reduce the number of progress messages:
<img width="839" alt="image" src="https://github.com/folke/noice.nvim/assets/62502207/9c1f2e68-9662-4c71-bcb1-cc96d48cbfbc">

**Comment by folke** [comment]
@MariaSolOs if you're experiencing the lua-ls issue where you get a ton of progress notifications on your screen, then make sure to update lua_ls. It has been fixed in there recently

**Comment by AndreM222** [comment]
> @MariaSolOs if you're experiencing the lua-ls issue where you get a ton of progress notifications on your screen, then make sure to update lua_ls. It has been fixed in there recently

For eslint_d is still a problem. but at least for now I can use MariaSolOs to ignore null-ls
