### ISSUE TITLE
Error running config for noice.nvim: ...ck/packer/opt/noice.nvim/lua/noice/config/highlights.lua:34

### ISSUE THREAD

**Issue by cscovino** [folke/noice.nvim#63]
**Describe the bug**
This [commit](https://github.com/folke/noice.nvim/commit/9ab738a834c01c7eaf2c320f8b4385a3fe94389a) causes packer throws an error:
```
packer.nvim: Error running config for noice.nvim: ...ck/packer/opt/noice.nvim/lua/noice/config/highlights.lua:34: invalid key: 
```
If I revert that commit it works fine.

**Which version of Neovim are you using?**
It happens with Nightly and Stable

**To Reproduce**
1. Install noice with default config
2. Open nvim

**Screenshots**
![Screen Shot 2022-10-14 at 14 51 14](https://user-images.githubusercontent.com/9748855/195909940-087eb89e-2b91-435c-89f0-b931b721a004.png)

**Noice Log**
Because this error noice does not initialize

<details>
<summary>Noice log</summary>
<pre>
paste log here
</pre>
</details>

**Comment by quantum-booty** [comment]
I can also replicate this error on latest nightly.

**Comment by folke** [comment]
Not home right now. Indeed that commit. There must be a special key in one of the highlight group links for the colorscheme you're using. Will check once I'm home.

Would help to know what key is causing this issue.can you run Noice log?

**Comment by quantum-booty** [comment]
Can't run Noice log because I don't think it was able to setup.

**Comment by cscovino** [comment]
I commented the colorscheme and I got this.

![Screen Shot 2022-10-14 at 16 12 21](https://user-images.githubusercontent.com/9748855/195923342-99a87d6b-f09b-4994-9913-b774870fdce5.png)

**Comment by pwntester** [comment]
Got the same issue, it seems caused by Noice linking not defined hl groups. For example, `Mini` is linked to `MsgArea` but in my case it is not defined (`MsgArea        xxx cleared`).   So `opts` returned by `vim.api.nvim_get_hl_by_name` does not contain the mandatory `foreground` and `background` keys. As a workaround, make sure that all the highlight groups linked in `highlights.lua` exists in your color theme

**Comment by folke** [comment]
I think I just fixed it. Can you check?

**Comment by chzerv** [comment]
Unfortunately 3e6bc74b662fcf1058a423b55be0717a66e89e3d doesn't seem to fix the issue.

Adding a simple `print` (this is in `highlights.lua`):

```lua
function M.setup()
  for hl, link in pairs(M.defaults) do
    local ok, opts = pcall(vim.api.nvim_get_hl_by_name, link, true)

    -- Debug
    print(hl, link, vim.inspect(opts))

    if not ok then
      opts = { link = link }
    end
    opts.default = true
    vim.api.nvim_set_hl(0, "Noice" .. hl, opts)
  end
end

```

 If a highlight group is not defined, `opts` looks like this:

```vim
Mini MsgArea {
  [true] = 6
}
```

**Comment by folke** [comment]
Right, forgot about these special `vim.type_idx` keys. Should be fixed now.

**Comment by chzerv** [comment]
Can confirm it is indeed fixed. Thank you so much!
